# Generated by Django 5.0.6 on 2024-06-24 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhistory',
            name='product',
            field=models.ManyToManyField(to='shop.productmodel'),
        ),
    ]
